# Generated by Django 3.2.12 on 2022-05-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('events_details', models.TextField(blank=True, null=True)),
                ('event_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('Gallery', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('image_name', models.CharField(blank=True, max_length=250, null=True)),
                ('edit_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('edit_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
