# Generated by Django 3.2.12 on 2022-05-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_detail_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
