# Generated by Django 3.2.12 on 2022-06-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220601_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.AddField(
            model_name='tag',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
