# Generated by Django 3.2.12 on 2022-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220601_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='featured',
            new_name='profile_pic',
        ),
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
