# Generated by Django 3.2.12 on 2022-06-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220602_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
