# Generated by Django 3.2.12 on 2022-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20220802_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('head', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('message', models.TextField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('head', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('head', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('head', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=200, null=True)),
                ('head', models.ImageField(blank=True, null=True, upload_to='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team_cc',
        ),
        migrations.DeleteModel(
            name='Team_founders',
        ),
        migrations.DeleteModel(
            name='Team_graphics',
        ),
        migrations.DeleteModel(
            name='Team_pr',
        ),
        migrations.DeleteModel(
            name='Team_smo',
        ),
        migrations.DeleteModel(
            name='Team_technical',
        ),
    ]
