# Generated by Django 3.2.12 on 2022-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20220803_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr',
            name='head',
        ),
        migrations.AddField(
            model_name='pr',
            name='profile_pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
