# Generated by Django 3.2.12 on 2022-08-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20220803_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technical',
            old_name='head',
            new_name='profile_pic2',
        ),
    ]
